server:
  port: 0

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shedlock;INIT=CREATE SCHEMA IF NOT EXISTS shedlock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  application:
    name: client

base:
  url: http://localhost:8086

data: AAAA, BBBB, CCCC, DDDD, EE

scheduling:
  enabled: true
